(deftheme bmax-tokyo
  "Created 2022-08-17.")

(custom-theme-set-faces
 'bmax-tokyo
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1a1b26" :foreground "#c0caf5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 133 :width normal))))
 '(cursor ((t (:background "#b4f9f8"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#b4f9f8"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#b4f9f8"))))
 '(highlight ((t (:foreground "#414868" :background "#b4f9f8"))))
 '(region ((t (:extend t :background "#414868"))))
 '(shadow ((t (:foreground "#9099c0"))))
 '(secondary-selection ((t (:extend t :background "#8189af"))))
 '(trailing-whitespace ((t (:background "#f7768e"))))
 '(font-lock-builtin-face ((t (:foreground "#f7768e"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#51587a"))))
 '(font-lock-constant-face ((t (:foreground "#ff9e64"))))
 '(font-lock-doc-face ((t (:foreground "#7c819b" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#9d7cd8"))))
 '(font-lock-keyword-face ((t (:foreground "#9d7cd8"))))
 '(font-lock-negation-char-face ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#7dcfff" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#9ece6a"))))
 '(font-lock-type-face ((t (:foreground "#c0caf5"))))
 '(font-lock-variable-name-face ((t (:foreground "#c0caf5"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#b4f9f8"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#8189af" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#a9b1d6" :background "#13141c"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#161620" :style nil) :background "#161620"))))
 '(mode-line-buffer-id ((t (:foreground "#b4f9f8"))))
 '(mode-line-emphasis ((t (:foreground "#b4f9f8"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#171822" :style nil) :foreground "#9099c0" :background "#171822"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#414868" :background "#f7768e"))))
 '(lazy-highlight ((t (:foreground "#414868" :background "#485d65"))))
 '(match ((t (:weight bold :foreground "#73daca" :background "#414868"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'bmax-tokyo)
