(deftheme bmax-purple-night
  "My awesome theme")

(defface my-default-face
  '((t :background "black" :foreground "white"))
  "Default-face"
  :group nil)

(let  ((black             "#000000")
       (white              "#ffffff")
       (none               "NONE")
       (bg_dark            "#1f2335")
       (bg                 "#181818")
       (bg_highlight       "#585858")
       (terminal_black     "#585858")
       (fg                 "#c0caf5")
       (fg_dark            "#a9b1d6")
       (fg_gutter          "#3b4261")
       (dark3              "#545c7e")
       (comment            "#565f89")
       (dark5              "#737aa2")
       (blue0              "#3d59a1")
       (blue               "#7aa2f7")
       (cyan               "#7dcfff")
       (blue1              "#2ac3de")
       (blue2              "#0db9d7")
       (blue5              "#89ddff")
       (blue6              "#B4F9F8")
       (blue7              "#394b70")
       (magenta            "#bb9af7")
       (magenta2           "#ff007c")
       ;;(purple             "#9d7cd8")
       (purple             "#9f5ce8")
       (orange             "#ff9e64")
       (yellow             "#e0af68")
       (green              "#9ece6a")
       (green1             "#73daca")
       (green2             "#41a6b5")
       (teal               "#1abc9c")
       (red                "#f7768e")
       (red1               "#db4b4b")
       (magit-add-fg       "#73daca")
       (magit-add-hl-bg    "#2b4146")
       (magit-add-bg       "#222e36")
       (magit-remove-fg    "#f7768e")
       (magit-remove-hl-bg "#7b3b47")
       (magit-remove-bg    "#4a232a"))

  ;;dddd
  (custom-theme-set-faces
   'bmax-purple-night
;;   `(default                           ((t (:inherit my-default-face                                     ))))
   `(default                           ((t (:foreground ,fg :background ,bg                              ))))
   `(line-number                       ((t (:foreground ,comment                                         ))))
   `(font-lock-comment-face            ((t (:foreground ,comment                                         ))))
   `(cursor                            ((t (:background ,fg                                              ))))
   `(region                            ((t (:background ,blue7                                           ))))
   `(mode-line                         ((t (:background ,fg_gutter                                       ))))
   `(line-number                       ((t (:foreground ,comment :background ,bg                         ))))
   `(highlight                         ((t (:background ,terminal_black                                  ))))
   `(font-lock-keyword-face            ((t (:foreground ,purple                                          ))))
   `(font-lock-constant-face           ((t (:foreground ,green                                           ))))
   `(font-lock-string-face             ((t (:foreground ,green                                           ))))
   `(font-lock-builtin-face            ((t (:foreground ,green                                           ))))
   `(font-lock-keyword-face            ((t (:foreground ,magenta :background ,bg                         ))))
   `(font-lock-comment-face            ((t (:foreground ,comment                                         ))))
   ;; web mode
   `(web-mode-html-tag-bracket-face    ((t (:foreground ,fg             :background ,bg                  ))))
   `(web-mode-html-tag-face            ((t (:foreground ,blue           :background ,bg                  ))))
   `(web-mode-html-attr-name-face      ((t (:foreground ,yellow         :background ,bg                  ))))
   `(web-mode-symbol-face              ((t (:foreground ,magenta        :background ,bg                  ))))

   ;; tree sitter
   `(tree-sitter-hl-face:punctuation   ((t (:foreground ,blue                                            ))))
   ;; magit
   `(magit-diff-context-highlight      ((t (:foreground ,fg              :background ,bg                 ))))
   `(magit-diff-removed-highlight      ((t (:foreground ,magit-remove-fg :background ,magit-remove-hl-bg ))))
   `(magit-diff-removed                ((t (:foreground ,magit-remove-fg :background ,magit-remove-bg    ))))
   `(magit-diff-added-highlight        ((t (:foreground ,magit-add-fg    :background ,magit-add-hl-bg    ))))
   `(magit-diff-added                  ((t (:foreground ,magit-add-fg    :background ,magit-add-bg       ))))
   `(magit-diff-hunk-heading-highlight ((t (:foreground ,bg              :background ,fg                 ))))
   `(magit-section-highlight           ((t (                             :background ,terminal_black     ))))
   `(magit-diff-removed                ((t (                             :background ,red1               ))))))

(provide-theme 'bmax-purple-night)
