(deftheme bmax-gruvbox-light
  "Created 2022-08-24.")

(custom-theme-set-faces
 'bmax-gruvbox-light
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#ffffd7" :foreground "#282828" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 152 :width normal :foundry "UKWN"))))
 '(cursor ((t (:background "#a89984"))))
 '(line-number ((t (:foreground "#af8787"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#427b58"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#a89984"))))
 '(highlight ((t (:foreground "#f0f0f0" :background "#a89984"))))
 '(region ((t (:extend t :background "#d9cea9"))))
 '(shadow ((t (:foreground "#504945"))))
 '(secondary-selection ((t (:extend t :background "#928374"))))
 '(trailing-whitespace ((t (:background "#9d0006"))))
 '(font-lock-builtin-face ((t (:foreground "#af0000"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#a89984"))))
 '(font-lock-constant-face ((t (:foreground "#8f3f71"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#79740e" :slant normal))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#b57614"))))
 '(font-lock-keyword-face ((t (:foreground "#875f5f" :inherit bold))))
 '(font-lock-negation-char-face ((t (:foreground "#076678" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#076678" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#076678" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#076678" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#878700"))))
 '(font-lock-type-face ((t (:foreground "#8f3f71"))))
 '(font-lock-variable-name-face ((t (:foreground "#076678"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#a89984"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#a89984" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#3c3836" :background "#ebdbb2"))))
 '(mode-line ((t (:box nil :background "#ebdbb2"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#a89984"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#a38780" :background "#e1d8b3"))))
 '(isearch ((t (:foreground "black" :background "#af3a03"))))
 '(isearch-fail ((t (:foreground "#282828" :background "#9d0006"))))
 '(lazy-highlight ((t (:weight bold :foreground "#1d2021" :background "#d5c4a1"))))
 '(match ((t (:weight bold :foreground "#79740e" :background "#f0f0f0"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(tree-sitter-hl-face:keyword ((t (:inherit (font-lock-builtin-face)))))
 '(tree-sitter-hl-face:function.call ((t (:slant normal))))
 '(tree-sitter-hl-face:method.call ((t (:slant normal))))
 '(tree-sitter-hl-face:property ((t (:slant normal :inherit (font-lock-constant-face)))))
 '(tree-sitter-hl-face:type ((t (:inherit (font-lock-keyword-face)))))
 )

(provide-theme 'bmax-gruvbox-light)
