(deftheme bmax-zenburn
  "Created 2022-08-23.")

(custom-theme-set-faces
 'bmax-zenburn
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#2f3332" :foreground "#DCDCDC" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 152 :width normal :foundry "UKWN" :family "VictorMono Nerd Font"))))
 '(cursor ((t (:foreground "#DCDCDC" :background "#FFFFEF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#F0DFAF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(highlight ((t (:background "#765576"))))
 '(region ((t (:extend t :background "#2B2B2B"))))
 '(shadow ((t (:foreground "#4F4F4F"))))
 '(secondary-selection ((t (:extend t :background "#494949"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#DCDCDC"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#F0DFAF"))))
 '(font-lock-negation-char-face ((t (:foreground "#8CD0D3" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#8CD0D3" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8CD0D3" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#8CD0D3" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#E0CF9F"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#D0BF8F"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:inherit default :foreground "#995599"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#DCDCDC" :background "#4F4F4F"))))
 '(mode-line ((t (:box nil :foreground "#8FB28F" :background "#2B2B2B"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#8CD0D3"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#989890" :background "#353535"))))
 '(isearch ((t (:weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCDC" :background "#8C5353"))))
 '(lazy-highlight ((t (:weight bold :foreground "#D0BF8F" :background "#383838"))))
 '(match ((t (:weight bold :foreground "#7F9F7F" :background "#000000"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'bmax-zenburn)
