(deftheme bmax-gruvbox
  "Created 2022-08-24.")

(custom-theme-set-faces
 'bmax-gruvbox
 '(default ((t ( :foundry "UKWN" :width normal :height 152 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#ebdbb2" :background "#282828" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#ebdbb2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#8ec07c"))))
 '(homoglyph ((t (:foreground "#fabd2f"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#b8bb26" :background "#282828"))))
 '(highlight ((t (:foreground "#fdf4c1" :background "#7c6f64"))))
 '(region ((t (:extend t :background "#504945"))))
 '(shadow ((t (:foreground "#7c6f64"))))
 '(secondary-selection ((t (:extend t :background "#3c3836"))))
 '(trailing-whitespace ((t (:background "#fb4933"))))


 '(font-lock-keyword-face ((t (:foreground "#fe8019" :inherit bold))))
 '(font-lock-builtin-face ((t (:foreground "#fb4933"))))

 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#7c6f64"))))
 '(font-lock-constant-face ((t (:foreground "#d3869b"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#fabd2f"))))

 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit font-lock-builtin-face))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#b8bb26"))))
 '(font-lock-type-face ((t (:foreground "#d3869b"))))
 '(font-lock-variable-name-face ((t (:foreground "#83a598"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#fb4933"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#076678"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#282828"))))
 '(header-line ((t (:box nil :foreground "#bdae93" :background "#282828" :inherit nil))))
 '(tooltip ((t (:foreground "#ebdbb2" :background "#3c3836"))))
 '(mode-line ((t (:box nil :foreground "#d5c4a1" :background "#665c54"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#a89984" :background "#3c3836"))))
 '(isearch ((t (:foreground "#000000" :background "#fe8019"))))
 '(isearch-fail ((t (:foreground "#fdf4c1" :background "#fb4933"))))
 '(lazy-highlight ((t (:foreground "#000000" :background "#fabd2f"))))
 '(match ((t (:foreground "#282828" :background "#83a598"))))
 '(next-error ((t (:inherit (region)))))
 '(tree-sitter-hl-face:keyword ((t (:inherit (font-lock-builtin-face)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'bmax-gruvbox)
